---
- hosts: webservers
  tasks:
    - name: Install Latest Apache
      apt: name=apache2 update_cache=yes state=latest
      tags: -Apache_tag

    - name: Install FirewallD
      apt: name=firewalld update_cache=true state=latest
      tags:
        - Firewall_tag

    - name: Start Apache
      service:
        name: apache2
        state: started
      tags:
        - startApache_tag

    - name: Start Firewall
      systemd:
        name: firewalld
        state: started

    - name: Add FirewallD
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

    - name: Reload Firewall Configuration For New Rule
      systemd:
        name: firewalld
        state: reloaded

    - name: Copy Html Page
      copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html/

    - name: restart Apache
      service:
        name: apache2
        state: restarted
      tags:
        - always
